--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBERSHIP
--------------------------------------------------------

  CREATE TABLE "MODERNIZE_T"."MEMBERSHIP" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PASS" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"MOBILE" VARCHAR2(30 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MODERNIZE_T.MEMBERSHIP
SET DEFINE OFF;
Insert into MODERNIZE_T.MEMBERSHIP (ID,PASS,NAME,EMAIL,MOBILE,REGIDATE) values ('tjoeun','1234','더조은IT','tj@tjoeun.com','010-1234-5678',to_date('24/07/18','RR/MM/DD'));
Insert into MODERNIZE_T.MEMBERSHIP (ID,PASS,NAME,EMAIL,MOBILE,REGIDATE) values ('asdf','asdf','asdf','asdf','asdf',to_date('24/07/18','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008428
--------------------------------------------------------

  CREATE UNIQUE INDEX "MODERNIZE_T"."SYS_C008428" ON "MODERNIZE_T"."MEMBERSHIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008428
--------------------------------------------------------

  CREATE UNIQUE INDEX "MODERNIZE_T"."SYS_C008428" ON "MODERNIZE_T"."MEMBERSHIP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBERSHIP
--------------------------------------------------------

  ALTER TABLE "MODERNIZE_T"."MEMBERSHIP" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "MODERNIZE_T"."MEMBERSHIP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MODERNIZE_T"."MEMBERSHIP" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MODERNIZE_T"."MEMBERSHIP" MODIFY ("MOBILE" NOT NULL ENABLE);
  ALTER TABLE "MODERNIZE_T"."MEMBERSHIP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
